-- Add 5 High-ROI Suite Skills to the skills table
INSERT INTO skills (
  id,
  name,
  version,
  category,
  description,
  author,
  metadata,
  contract,
  requirements,
  implementation_type,
  implementation_ref,
  configuration,
  tags,
  certified,
  active,
  is_core_skill,
  base_cost_pence,
  token_usage_estimate,
  execution_time_ms,
  value_multiplier,
  skill_tier,
  applicable_products,
  dependencies,
  created_at,
  updated_at
) VALUES

-- ============ SOCIAL MEDIA INTELLIGENCE SUITE ============
(
  gen_random_uuid(),
  'viral-content-predictor_v1',
  '1.0.0',
  'social-media',
  'Predict content virality potential before posting using AI analysis',
  'Intelagent',
  '{"category": "social-intelligence", "accuracy": "78%"}',
  '{"inputs": {"content": "string", "contentType": "string", "platform": "array"}, "outputs": {"viralityScore": "number", "predictions": "object", "recommendations": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/social/viral-predictor',
  '{"supportedPlatforms": ["twitter", "instagram", "tiktok", "linkedin", "facebook", "youtube"]}',
  ARRAY['viral', 'prediction', 'social-media', 'content', 'ai-analysis', 'engagement'],
  true,
  true,
  false,
  8000,
  500,
  3000,
  2.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'social-sentiment-analyzer_v1',
  '1.0.0',
  'social-media',
  'Real-time brand sentiment analysis across social platforms',
  'Intelagent',
  '{"category": "social-intelligence", "real-time": true}',
  '{"inputs": {"brand": "string", "platforms": "array"}, "outputs": {"sentiment": "object", "trends": "array", "alerts": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/social/sentiment-analyzer',
  '{"updateFrequency": "real-time", "languages": ["en", "es", "fr", "de"]}',
  ARRAY['sentiment', 'brand', 'monitoring', 'social-media', 'analytics'],
  true,
  true,
  false,
  6000,
  300,
  2000,
  2.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'influencer-identifier_v1',
  '1.0.0',
  'social-media',
  'Find and analyze micro/macro influencers in any niche',
  'Intelagent',
  '{"category": "social-intelligence", "database_size": "10M+"}',
  '{"inputs": {"niche": "string", "platform": "string"}, "outputs": {"influencers": "array", "analytics": "object", "contactInfo": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/social/influencer-finder',
  '{"minFollowers": 1000, "maxFollowers": 10000000}',
  ARRAY['influencer', 'discovery', 'outreach', 'social-media', 'marketing'],
  true,
  true,
  false,
  10000,
  0,
  5000,
  3.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'hashtag-optimizer_v1',
  '1.0.0',
  'social-media',
  'AI-powered hashtag research and optimization for maximum reach',
  'Intelagent',
  '{"category": "social-intelligence", "ai_model": "custom"}',
  '{"inputs": {"content": "string", "platform": "string"}, "outputs": {"hashtags": "array", "reach": "number", "competition": "object"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/social/hashtag-optimizer',
  '{"maxHashtags": 30, "trendingAnalysis": true}',
  ARRAY['hashtag', 'optimization', 'reach', 'discovery', 'trending'],
  true,
  true,
  false,
  4000,
  200,
  1500,
  1.5,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'social-crisis-detector_v1',
  '1.0.0',
  'social-media',
  'Early warning system for PR issues and brand crises',
  'Intelagent',
  '{"category": "social-intelligence", "alert_speed": "instant"}',
  '{"inputs": {"brand": "string", "platforms": "array"}, "outputs": {"threats": "array", "severity": "number", "recommendations": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/social/crisis-detector',
  '{"monitoringInterval": 60, "alertChannels": ["email", "sms", "slack"]}',
  ARRAY['crisis', 'pr', 'monitoring', 'alert', 'reputation'],
  true,
  true,
  false,
  12000,
  0,
  1000,
  4.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'competitor-social-spy_v1',
  '1.0.0',
  'social-media',
  'Track and analyze competitor social media strategies',
  'Intelagent',
  '{"category": "social-intelligence", "competitive_intel": true}',
  '{"inputs": {"competitors": "array", "platforms": "array"}, "outputs": {"strategies": "object", "performance": "object", "opportunities": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/social/competitor-spy',
  '{"trackingDepth": "comprehensive", "historicalData": 90}',
  ARRAY['competitor', 'analysis', 'tracking', 'strategy', 'insights'],
  true,
  true,
  false,
  8000,
  0,
  4000,
  2.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

-- ============ E-COMMERCE INTELLIGENCE SUITE ============
(
  gen_random_uuid(),
  'product-feed-optimizer_v1',
  '1.0.0',
  'ecommerce',
  'Optimize product feeds for Google Shopping, Facebook, and Amazon',
  'Intelagent',
  '{"category": "ecommerce", "platforms": ["google", "facebook", "amazon"]}',
  '{"inputs": {"feedUrl": "string", "platform": "string"}, "outputs": {"optimizedFeed": "object", "issues": "array", "recommendations": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/ecommerce/feed-optimizer',
  '{"maxProducts": 100000, "formats": ["xml", "csv", "json"]}',
  ARRAY['product-feed', 'shopping', 'optimization', 'marketplace', 'google-shopping'],
  true,
  true,
  false,
  6000,
  0,
  3000,
  2.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'marketplace-seo_v1',
  '1.0.0',
  'ecommerce',
  'Optimize listings for Amazon, eBay, Etsy marketplaces',
  'Intelagent',
  '{"category": "ecommerce", "marketplaces": ["amazon", "ebay", "etsy"]}',
  '{"inputs": {"products": "array", "marketplace": "string"}, "outputs": {"optimizedListings": "array", "keywords": "array", "competitorAnalysis": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/ecommerce/marketplace-seo',
  '{"a9Algorithm": true, "bestMatchOptimization": true}',
  ARRAY['marketplace', 'amazon', 'ebay', 'etsy', 'optimization'],
  true,
  true,
  false,
  7000,
  300,
  2500,
  2.2,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'price-intelligence_v1',
  '1.0.0',
  'ecommerce',
  'Real-time competitor price monitoring and dynamic pricing',
  'Intelagent',
  '{"category": "ecommerce", "monitoring": "real-time"}',
  '{"inputs": {"products": "array", "competitors": "array"}, "outputs": {"prices": "object", "recommendations": "array", "alerts": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/ecommerce/price-intelligence',
  '{"updateFrequency": 3600, "pricingStrategies": ["competitive", "value", "premium"]}',
  ARRAY['pricing', 'monitoring', 'competition', 'dynamic-pricing', 'intelligence'],
  true,
  true,
  false,
  5000,
  0,
  2000,
  2.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'review-sentiment-analyzer_v1',
  '1.0.0',
  'ecommerce',
  'Aggregate and analyze product reviews across platforms',
  'Intelagent',
  '{"category": "ecommerce", "nlp_model": "advanced"}',
  '{"inputs": {"productId": "string", "platforms": "array"}, "outputs": {"sentiment": "object", "themes": "array", "improvements": "array"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/ecommerce/review-analyzer',
  '{"languages": ["en", "es", "fr", "de", "it"]}',
  ARRAY['reviews', 'sentiment', 'analysis', 'reputation', 'feedback'],
  true,
  true,
  false,
  4000,
  200,
  1500,
  1.8,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'abandoned-cart-predictor_v1',
  '1.0.0',
  'ecommerce',
  'Identify high-risk checkouts and prevent cart abandonment',
  'Intelagent',
  '{"category": "ecommerce", "ml_model": "predictive"}',
  '{"inputs": {"sessionData": "object", "userBehavior": "object"}, "outputs": {"riskScore": "number", "reasons": "array", "interventions": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/ecommerce/cart-predictor',
  '{"predictionAccuracy": "85%", "interventionTypes": ["email", "popup", "discount"]}',
  ARRAY['cart', 'abandonment', 'prediction', 'recovery', 'conversion'],
  true,
  true,
  false,
  8000,
  0,
  1000,
  3.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'product-description-generator_v1',
  '1.0.0',
  'ecommerce',
  'AI-powered product descriptions at scale',
  'Intelagent',
  '{"category": "ecommerce", "ai_model": "gpt-4"}',
  '{"inputs": {"productData": "object"}, "outputs": {"description": "string", "features": "array", "seoOptimized": "boolean"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/ecommerce/description-generator',
  '{"maxLength": 2000, "tones": ["professional", "casual", "luxury"]}',
  ARRAY['product', 'description', 'generation', 'ai', 'content'],
  true,
  true,
  false,
  5000,
  800,
  2000,
  2.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

-- ============ VIDEO & PODCAST SEO SUITE ============
(
  gen_random_uuid(),
  'youtube-seo-optimizer_v1',
  '1.0.0',
  'video',
  'Optimize titles, descriptions, tags, and thumbnails for YouTube',
  'Intelagent',
  '{"category": "video-seo", "platform": "youtube"}',
  '{"inputs": {"videoUrl": "string"}, "outputs": {"optimizations": "object", "tags": "array", "thumbnailSuggestions": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/video/youtube-optimizer',
  '{"algorithmVersion": "2024", "competitorAnalysis": true}',
  ARRAY['youtube', 'seo', 'video', 'optimization', 'thumbnails'],
  true,
  true,
  false,
  7000,
  0,
  3000,
  2.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'podcast-seo-enhancer_v1',
  '1.0.0',
  'video',
  'Optimize podcasts for directories and search engines',
  'Intelagent',
  '{"category": "audio-seo", "directories": ["apple", "spotify", "google"]}',
  '{"inputs": {"podcastUrl": "string", "episodeData": "object"}, "outputs": {"optimizations": "object", "keywords": "array", "distribution": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/video/podcast-enhancer',
  '{"transcriptionIncluded": true, "rssOptimization": true}',
  ARRAY['podcast', 'seo', 'audio', 'optimization', 'directories'],
  true,
  true,
  false,
  5000,
  0,
  2000,
  2.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'video-transcript-optimizer_v1',
  '1.0.0',
  'video',
  'Generate and optimize SEO-friendly video transcriptions',
  'Intelagent',
  '{"category": "video-seo", "accuracy": "95%"}',
  '{"inputs": {"videoUrl": "string"}, "outputs": {"transcript": "string", "captions": "object", "keywords": "array"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/video/transcript-optimizer',
  '{"formats": ["srt", "vtt", "txt"], "languages": 50}',
  ARRAY['transcript', 'video', 'seo', 'captions', 'accessibility'],
  true,
  true,
  false,
  6000,
  500,
  4000,
  1.8,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'video-chapter-generator_v1',
  '1.0.0',
  'video',
  'Auto-generate timestamps and chapters for videos',
  'Intelagent',
  '{"category": "video-seo", "ai_powered": true}',
  '{"inputs": {"videoUrl": "string"}, "outputs": {"chapters": "array", "timestamps": "array", "description": "string"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/video/chapter-generator',
  '{"maxChapters": 50, "minChapterLength": 30}',
  ARRAY['chapters', 'timestamps', 'video', 'navigation', 'ux'],
  true,
  true,
  false,
  4000,
  200,
  2000,
  1.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'shorts-tiktok-optimizer_v1',
  '1.0.0',
  'video',
  'Optimize for short-form video algorithms',
  'Intelagent',
  '{"category": "video-seo", "platforms": ["youtube-shorts", "tiktok", "reels"]}',
  '{"inputs": {"videoContent": "object", "platform": "string"}, "outputs": {"optimizations": "object", "trends": "array", "music": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/video/shorts-optimizer',
  '{"trendAnalysis": true, "viralPrediction": true}',
  ARRAY['shorts', 'tiktok', 'reels', 'short-form', 'viral'],
  true,
  true,
  false,
  8000,
  300,
  2500,
  3.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'video-accessibility-checker_v1',
  '1.0.0',
  'video',
  'Check and improve video accessibility (captions, audio descriptions)',
  'Intelagent',
  '{"category": "video-seo", "standards": ["wcag", "ada"]}',
  '{"inputs": {"videoUrl": "string"}, "outputs": {"issues": "array", "score": "number", "fixes": "array"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/video/accessibility-checker',
  '{"autoFix": true, "multiLanguage": true}',
  ARRAY['accessibility', 'captions', 'ada', 'wcag', 'compliance'],
  true,
  true,
  false,
  5000,
  0,
  3000,
  1.8,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

-- ============ DATA ENRICHMENT & LEAD INTELLIGENCE ============
(
  gen_random_uuid(),
  'company-enrichment_v1',
  '1.0.0',
  'data-enrichment',
  'Get complete firmographics from domain or company name',
  'Intelagent',
  '{"category": "b2b-intelligence", "data_sources": 50}',
  '{"inputs": {"domain": "string"}, "outputs": {"company": "object", "contacts": "array", "technographics": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/enrichment/company-data',
  '{"dataPoints": 100, "accuracy": "92%"}',
  ARRAY['enrichment', 'firmographics', 'b2b', 'company-data', 'intelligence'],
  true,
  true,
  false,
  10000,
  0,
  2000,
  3.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'lead-scoring-ai_v1',
  '1.0.0',
  'data-enrichment',
  'Predictive lead scoring using machine learning',
  'Intelagent',
  '{"category": "b2b-intelligence", "ml_model": "gradient-boost"}',
  '{"inputs": {"leadData": "object"}, "outputs": {"score": "number", "factors": "object", "recommendations": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/enrichment/lead-scoring',
  '{"scoringAccuracy": "87%", "customModels": true}',
  ARRAY['lead-scoring', 'ai', 'prediction', 'sales', 'qualification'],
  true,
  true,
  false,
  6000,
  100,
  1500,
  2.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'email-finder-verifier_v1',
  '1.0.0',
  'data-enrichment',
  'Find and verify business email addresses',
  'Intelagent',
  '{"category": "b2b-intelligence", "verification": "real-time"}',
  '{"inputs": {"name": "string", "company": "string"}, "outputs": {"email": "string", "verified": "boolean", "confidence": "number"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/enrichment/email-finder',
  '{"verificationMethods": ["smtp", "dns", "pattern"], "catchAll": true}',
  ARRAY['email', 'finder', 'verification', 'outreach', 'b2b'],
  true,
  true,
  false,
  3000,
  0,
  1000,
  1.5,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'technographic-profiler_v1',
  '1.0.0',
  'data-enrichment',
  'Identify technology stack of any company',
  'Intelagent',
  '{"category": "b2b-intelligence", "technologies": 5000}',
  '{"inputs": {"domain": "string"}, "outputs": {"techStack": "array", "categories": "object", "spend": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/enrichment/technographics',
  '{"detectionMethods": ["dns", "headers", "scripts", "pixels"]}',
  ARRAY['technographics', 'tech-stack', 'intelligence', 'b2b', 'profiling'],
  true,
  true,
  false,
  7000,
  0,
  3000,
  2.2,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'intent-data-analyzer_v1',
  '1.0.0',
  'data-enrichment',
  'Identify buying intent signals from multiple sources',
  'Intelagent',
  '{"category": "b2b-intelligence", "signal_sources": 15}',
  '{"inputs": {"company": "string", "industry": "string"}, "outputs": {"intentScore": "number", "signals": "array", "timing": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/enrichment/intent-data',
  '{"signalTypes": ["content", "search", "social", "technographic"]}',
  ARRAY['intent', 'signals', 'buying', 'prediction', 'b2b'],
  true,
  true,
  false,
  12000,
  0,
  4000,
  4.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'decision-maker-identifier_v1',
  '1.0.0',
  'data-enrichment',
  'Find key stakeholders and decision makers in companies',
  'Intelagent',
  '{"category": "b2b-intelligence", "org_chart": true}',
  '{"inputs": {"company": "string"}, "outputs": {"decisionMakers": "array", "orgChart": "object", "contactInfo": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/enrichment/decision-makers',
  '{"seniorityLevels": ["c-suite", "vp", "director", "manager"]}',
  ARRAY['stakeholders', 'decision-makers', 'contacts', 'b2b', 'org-chart'],
  true,
  true,
  false,
  8000,
  0,
  2500,
  3.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

-- ============ LEGAL & COMPLIANCE AUTOMATION ============
(
  gen_random_uuid(),
  'gdpr-compliance-scanner_v1',
  '1.0.0',
  'legal-compliance',
  'Automated GDPR compliance audit and recommendations',
  'Intelagent',
  '{"category": "compliance", "regulation": "gdpr"}',
  '{"inputs": {"websiteUrl": "string"}, "outputs": {"issues": "array", "score": "number", "recommendations": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/compliance/gdpr-scanner',
  '{"articles": ["6", "7", "13", "14", "15-22", "25", "32", "33", "34"]}',
  ARRAY['gdpr', 'compliance', 'privacy', 'audit', 'legal'],
  true,
  true,
  false,
  10000,
  0,
  5000,
  3.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'accessibility-wcag-checker_v1',
  '1.0.0',
  'legal-compliance',
  'Check WCAG 2.1/3.0 compliance and accessibility issues',
  'Intelagent',
  '{"category": "compliance", "standards": ["wcag21", "wcag30", "ada"]}',
  '{"inputs": {"url": "string"}, "outputs": {"violations": "array", "score": "number", "fixes": "object"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/compliance/accessibility-checker',
  '{"levels": ["A", "AA", "AAA"], "autoFix": true}',
  ARRAY['accessibility', 'wcag', 'ada', 'compliance', 'a11y'],
  true,
  true,
  false,
  6000,
  0,
  4000,
  2.0,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'copyright-infringement-detector_v1',
  '1.0.0',
  'legal-compliance',
  'Detect image and text plagiarism or copyright violations',
  'Intelagent',
  '{"category": "compliance", "detection_methods": ["image", "text", "code"]}',
  '{"inputs": {"content": "object"}, "outputs": {"violations": "array", "sources": "array", "riskLevel": "string"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/compliance/copyright-detector',
  '{"database": "100M+ sources", "accuracy": "94%"}',
  ARRAY['copyright', 'plagiarism', 'infringement', 'dmca', 'detection'],
  true,
  true,
  false,
  8000,
  0,
  3000,
  2.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'terms-generator-ai_v1',
  '1.0.0',
  'legal-compliance',
  'Generate custom legal documents (Terms, Privacy Policy, etc)',
  'Intelagent',
  '{"category": "compliance", "document_types": 15}',
  '{"inputs": {"businessType": "string", "jurisdiction": "string"}, "outputs": {"document": "string", "customizations": "array", "warnings": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/compliance/terms-generator',
  '{"languages": 25, "jurisdictions": 50, "updates": "automatic"}',
  ARRAY['terms', 'privacy-policy', 'legal', 'generator', 'documents'],
  true,
  true,
  false,
  15000,
  2000,
  3000,
  4.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'cookie-consent-optimizer_v1',
  '1.0.0',
  'legal-compliance',
  'Optimize cookie consent for compliance and conversion',
  'Intelagent',
  '{"category": "compliance", "regulations": ["gdpr", "ccpa", "pecr"]}',
  '{"inputs": {"websiteUrl": "string"}, "outputs": {"configuration": "object", "consent_flow": "object", "ab_tests": "array"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/compliance/cookie-optimizer',
  '{"consentRateOptimization": true, "darkPatternPrevention": true}',
  ARRAY['cookies', 'consent', 'gdpr', 'ccpa', 'optimization'],
  true,
  true,
  false,
  5000,
  0,
  2000,
  1.8,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'ai-content-disclosure_v1',
  '1.0.0',
  'legal-compliance',
  'Ensure compliance with AI-generated content regulations',
  'Intelagent',
  '{"category": "compliance", "ai_regulations": ["eu-ai-act", "ftc", "china"]}',
  '{"inputs": {"content": "string"}, "outputs": {"disclosure": "string", "placement": "object", "compliance": "boolean"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/compliance/ai-disclosure',
  '{"autoDetection": true, "multilingual": true}',
  ARRAY['ai', 'disclosure', 'compliance', 'regulation', 'transparency'],
  true,
  true,
  false,
  4000,
  100,
  1500,
  2.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
)

ON CONFLICT (name, version) DO UPDATE SET
  description = EXCLUDED.description,
  metadata = EXCLUDED.metadata,
  contract = EXCLUDED.contract,
  configuration = EXCLUDED.configuration,
  tags = EXCLUDED.tags,
  base_cost_pence = EXCLUDED.base_cost_pence,
  skill_tier = EXCLUDED.skill_tier,
  updated_at = NOW();