-- Add multilingual/SEO skills to the skills table
INSERT INTO skills (
  id,
  name,
  version,
  category,
  description,
  author,
  metadata,
  contract,
  requirements,
  implementation_type,
  implementation_ref,
  configuration,
  tags,
  certified,
  active,
  is_core_skill,
  base_cost_pence,
  token_usage_estimate,
  execution_time_ms,
  value_multiplier,
  skill_tier,
  applicable_products,
  dependencies,
  created_at,
  updated_at
) VALUES
(
  gen_random_uuid(),
  'translate-content_v1',
  '1.0.0',
  'communication',
  'Translate web pages or HTML content with advanced caching and translation memory',
  'Intelagent',
  '{"provider": "multilingual-service", "supports": ["openai", "deepl", "google"]}',
  '{"inputs": {"locale": "string", "url": "string?", "html": "string?"}, "outputs": {"html": "string", "htmlHandle": "string", "metadata": "object"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'external_service',
  'https://intelaglot.workers.dev/api/skills/translate-content',
  '{"supportedLocales": ["en", "es", "fr", "de", "it", "pt", "ja", "zh", "ko", "ru", "ar"], "cacheEnabled": true}',
  ARRAY['translation', 'multilingual', 'i18n', 'localization', 'seo'],
  true,
  true,
  false,
  5000,
  500,
  2000,
  1.5,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'generate-sitemap_v1',
  '1.0.0',
  'seo',
  'Generate localized sitemaps for SEO optimization across multiple languages',
  'Intelagent',
  '{"provider": "multilingual-service", "output": "xml"}',
  '{"inputs": {"locales": "string[]", "baseUrl": "string?", "urls": "string[]?"}, "outputs": {"sitemapIndex": "string", "localizedSitemaps": "object", "sitemapHandle": "string"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'external_service',
  'https://intelaglot.workers.dev/api/skills/generate-sitemap',
  '{"maxUrlsPerSitemap": 50000, "compressionSupported": true}',
  ARRAY['sitemap', 'seo', 'multilingual', 'localization', 'indexing'],
  true,
  true,
  false,
  3000,
  100,
  1000,
  1.2,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'inject-hreflang_v1',
  '1.0.0',
  'seo',
  'Generate and inject hreflang tags for multilingual SEO optimization',
  'Intelagent',
  '{"provider": "multilingual-service", "output": "html"}',
  '{"inputs": {"url": "string", "locales": "string[]", "currentLocale": "string?"}, "outputs": {"headFragment": "string", "metadata": "object"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'external_service',
  'https://intelaglot.workers.dev/api/skills/inject-hreflang',
  '{"hreflangFormats": ["standard", "x-default"], "canonicalSupport": true}',
  ARRAY['hreflang', 'seo', 'multilingual', 'localization', 'international'],
  true,
  true,
  false,
  2000,
  50,
  500,
  1.0,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
)
ON CONFLICT (name, version) DO UPDATE SET
  description = EXCLUDED.description,
  metadata = EXCLUDED.metadata,
  contract = EXCLUDED.contract,
  configuration = EXCLUDED.configuration,
  tags = EXCLUDED.tags,
  updated_at = NOW();