-- Add comprehensive SEO skills to the skills table
INSERT INTO skills (
  id,
  name,
  version,
  category,
  description,
  author,
  metadata,
  contract,
  requirements,
  implementation_type,
  implementation_ref,
  configuration,
  tags,
  certified,
  active,
  is_core_skill,
  base_cost_pence,
  token_usage_estimate,
  execution_time_ms,
  value_multiplier,
  skill_tier,
  applicable_products,
  dependencies,
  created_at,
  updated_at
) VALUES

-- Traditional SEO Skills
(
  gen_random_uuid(),
  'technical-seo-audit_v1',
  '1.0.0',
  'seo',
  'Comprehensive technical SEO analysis including crawlability, indexability, performance, and security',
  'Intelagent',
  '{"category": "traditional-seo", "complexity": "high"}',
  '{"inputs": {"url": "string", "crawlDepth": "number?", "includeSubdomains": "boolean?"}, "outputs": {"audit": "object", "score": "number", "recommendations": "array"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/seo/technical-audit',
  '{"maxCrawlDepth": 100, "checkTypes": ["crawlability", "indexability", "performance", "security", "structured-data"]}',
  ARRAY['seo', 'technical', 'audit', 'crawlability', 'performance', 'core-web-vitals'],
  true,
  true,
  false,
  10000,
  0,
  5000,
  2.0,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'keyword-research-pro_v1',
  '1.0.0',
  'seo',
  'Advanced keyword research with competitor analysis and AI search visibility scoring',
  'Intelagent',
  '{"category": "traditional-seo", "data_sources": ["google", "bing", "ai-systems"]}',
  '{"inputs": {"seedKeywords": "array", "locale": "string", "competitors": "array?"}, "outputs": {"keywords": "array", "questions": "array", "gaps": "array", "clusters": "array"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/seo/keyword-research',
  '{"maxKeywords": 1000, "includeAIVisibility": true}',
  ARRAY['keywords', 'research', 'competition', 'search-volume', 'intent'],
  true,
  true,
  false,
  8000,
  0,
  3000,
  1.8,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'backlink-analyzer_v1',
  '1.0.0',
  'seo',
  'Comprehensive backlink analysis with toxic link detection and opportunity identification',
  'Intelagent',
  '{"category": "traditional-seo", "analysis_depth": "comprehensive"}',
  '{"inputs": {"domain": "string", "competitors": "array?"}, "outputs": {"profile": "object", "links": "array", "opportunities": "array", "toxicLinks": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/backlink-analyzer',
  '{"maxLinks": 10000, "toxicScoreThreshold": 30}',
  ARRAY['backlinks', 'link-building', 'domain-authority', 'toxic-links'],
  true,
  true,
  false,
  12000,
  0,
  8000,
  2.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'local-seo-optimizer_v1',
  '1.0.0',
  'seo',
  'Local search optimization and Google My Business management',
  'Intelagent',
  '{"category": "traditional-seo", "platforms": ["gmb", "apple-maps", "bing-places"]}',
  '{"inputs": {"businessName": "string", "location": "string"}, "outputs": {"gmbOptimization": "object", "citations": "object", "reviews": "object", "localRankings": "object"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/seo/local-optimizer',
  '{"citationSources": 50, "reviewPlatforms": 10}',
  ARRAY['local-seo', 'gmb', 'citations', 'reviews', 'map-pack'],
  true,
  true,
  false,
  6000,
  0,
  4000,
  1.5,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

-- AI Search Optimization Skills
(
  gen_random_uuid(),
  'ai-search-optimizer_v1',
  '1.0.0',
  'seo',
  'Optimize content for AI chatbots and answer engines like ChatGPT, Perplexity, Claude, and Bard',
  'Intelagent',
  '{"category": "ai-seo", "systems": ["chatgpt", "perplexity", "claude", "bard", "bing-chat"]}',
  '{"inputs": {"content": "string", "targetSystems": "array?", "optimizationGoals": "array?"}, "outputs": {"optimizations": "object", "aiFriendlyVersion": "string", "structuredQAPairs": "array", "scores": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/ai-optimizer',
  '{"maxContentLength": 50000, "supportedFormats": ["text", "markdown", "html"]}',
  ARRAY['ai-seo', 'chatgpt', 'perplexity', 'claude', 'bard', 'answer-engine', 'llm-optimization'],
  true,
  true,
  false,
  15000,
  1000,
  6000,
  3.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'llm-training-optimizer_v1',
  '1.0.0',
  'seo',
  'Ensure content is optimized for LLM training datasets',
  'Intelagent',
  '{"category": "ai-seo", "optimization_type": "training-data"}',
  '{"inputs": {"content": "string", "format": "string?"}, "outputs": {"datasetReadiness": "object", "contentImprovements": "object", "syntheticDataGeneration": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/llm-training',
  '{"formats": ["markdown", "json", "plaintext"]}',
  ARRAY['llm', 'training-data', 'dataset', 'ai-optimization'],
  true,
  true,
  false,
  10000,
  500,
  4000,
  2.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'rag-optimization_v1',
  '1.0.0',
  'seo',
  'Optimize content for Retrieval-Augmented Generation systems',
  'Intelagent',
  '{"category": "ai-seo", "optimization_type": "rag"}',
  '{"inputs": {"content": "string", "chunkSize": "number?", "overlapRatio": "number?"}, "outputs": {"chunkingStrategy": "object", "embeddingOptimization": "object", "retrievalEnhancement": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/rag-optimization',
  '{"defaultChunkSize": 512, "maxOverlap": 0.2}',
  ARRAY['rag', 'retrieval', 'embeddings', 'vector-search', 'semantic'],
  true,
  true,
  false,
  8000,
  300,
  3000,
  1.8,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

-- Structured Data & Knowledge Graph Skills
(
  gen_random_uuid(),
  'schema-markup-generator_v1',
  '1.0.0',
  'seo',
  'Generate comprehensive schema.org markup for rich results',
  'Intelagent',
  '{"category": "structured-data", "formats": ["json-ld", "microdata", "rdfa"]}',
  '{"inputs": {"url": "string", "schemaTypes": "array?"}, "outputs": {"schemas": "array", "knowledgeGraph": "object", "richResults": "object"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/seo/schema-generator',
  '{"supportedTypes": ["Article", "Product", "LocalBusiness", "Event", "Recipe", "FAQ", "HowTo"]}',
  ARRAY['schema', 'structured-data', 'rich-results', 'json-ld', 'knowledge-graph'],
  true,
  true,
  false,
  5000,
  0,
  2000,
  1.5,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'entity-extractor_v1',
  '1.0.0',
  'seo',
  'Extract and link entities for knowledge graphs',
  'Intelagent',
  '{"category": "structured-data", "nlp_model": "advanced"}',
  '{"inputs": {"content": "string", "entityTypes": "array?"}, "outputs": {"entities": "array", "relationships": "array", "topics": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/entity-extractor',
  '{"entityTypes": ["person", "organization", "place", "product", "event"], "linkToWikidata": true}',
  ARRAY['entities', 'ner', 'knowledge-graph', 'wikidata', 'relationships'],
  true,
  true,
  false,
  7000,
  200,
  3000,
  1.7,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

-- Voice & Visual Search Skills
(
  gen_random_uuid(),
  'voice-search-optimizer_v1',
  '1.0.0',
  'seo',
  'Optimize for voice assistants and smart speakers',
  'Intelagent',
  '{"category": "voice-search", "assistants": ["alexa", "siri", "google-assistant"]}',
  '{"inputs": {"content": "string", "targetAssistants": "array?"}, "outputs": {"conversationalKeywords": "array", "featuredSnippetOptimization": "object", "speakableMarkup": "object", "localVoiceQueries": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/voice-optimizer',
  '{"naturalLanguageProcessing": true, "pronunciationHints": true}',
  ARRAY['voice-search', 'alexa', 'siri', 'google-assistant', 'conversational'],
  true,
  true,
  false,
  6000,
  100,
  2500,
  1.6,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'visual-search-optimizer_v1',
  '1.0.0',
  'seo',
  'Optimize images and videos for visual search',
  'Intelagent',
  '{"category": "visual-search", "platforms": ["google-lens", "pinterest", "bing-visual"]}',
  '{"inputs": {"mediaUrls": "array", "generateAltText": "boolean?"}, "outputs": {"images": "array", "videos": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/visual-optimizer',
  '{"imageFormats": ["jpg", "png", "webp"], "videoFormats": ["mp4", "webm"]}',
  ARRAY['visual-search', 'image-seo', 'video-seo', 'google-lens', 'pinterest'],
  true,
  true,
  false,
  8000,
  0,
  5000,
  1.8,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

-- E-E-A-T & Authority Skills
(
  gen_random_uuid(),
  'eeat-scorer_v1',
  '1.0.0',
  'seo',
  'Evaluate and improve Experience, Expertise, Authoritativeness, and Trustworthiness signals',
  'Intelagent',
  '{"category": "authority", "signals": ["experience", "expertise", "authoritativeness", "trustworthiness"]}',
  '{"inputs": {"url": "string", "authorProfile": "object?"}, "outputs": {"scores": "object", "signals": "object", "improvements": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/eeat-scorer',
  '{"scoringAlgorithm": "google-quality-guidelines-2024"}',
  ARRAY['eeat', 'authority', 'trust', 'expertise', 'google-quality'],
  true,
  true,
  false,
  7000,
  0,
  3500,
  2.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'author-authority-builder_v1',
  '1.0.0',
  'seo',
  'Build author profiles and authority signals',
  'Intelagent',
  '{"category": "authority", "profile_elements": ["bio", "credentials", "publications"]}',
  '{"inputs": {"authorName": "string", "expertiseAreas": "array?"}, "outputs": {"authorProfile": "object", "contentAttribution": "object", "authorityBuilding": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/author-builder',
  '{"profileEnrichment": true, "opportunityDiscovery": true}',
  ARRAY['author', 'authority', 'expertise', 'thought-leadership', 'byline'],
  true,
  true,
  false,
  5000,
  0,
  2000,
  1.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

-- Performance & Technical Skills
(
  gen_random_uuid(),
  'core-web-vitals-optimizer_v1',
  '1.0.0',
  'seo',
  'Optimize Core Web Vitals metrics (LCP, FID, CLS, INP)',
  'Intelagent',
  '{"category": "performance", "metrics": ["lcp", "fid", "cls", "inp"]}',
  '{"inputs": {"url": "string", "device": "string?"}, "outputs": {"currentMetrics": "object", "optimizations": "object", "resourceHints": "object"}}',
  '{"tier": "Custom", "minLicenseLevel": "Custom"}',
  'internal_service',
  'skills-orchestrator/seo/cwv-optimizer',
  '{"lighthouse": true, "crux": true}',
  ARRAY['core-web-vitals', 'performance', 'lcp', 'fid', 'cls', 'page-speed'],
  true,
  true,
  false,
  8000,
  0,
  6000,
  2.0,
  'premium',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'javascript-seo-analyzer_v1',
  '1.0.0',
  'seo',
  'Analyze JavaScript rendering and SEO impact',
  'Intelagent',
  '{"category": "technical", "rendering_methods": ["csr", "ssr", "ssg", "isr"]}',
  '{"inputs": {"url": "string", "framework": "string?"}, "outputs": {"rendering": "object", "contentAvailability": "object", "crawlability": "object", "recommendations": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/js-analyzer',
  '{"frameworks": ["react", "vue", "angular", "nextjs", "nuxt"]}',
  ARRAY['javascript', 'spa', 'ssr', 'rendering', 'crawlability'],
  true,
  true,
  false,
  6000,
  0,
  4000,
  1.8,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

-- Content Intelligence Skills
(
  gen_random_uuid(),
  'content-gap-analyzer_v1',
  '1.0.0',
  'seo',
  'Identify content gaps and opportunities',
  'Intelagent',
  '{"category": "content", "analysis_type": "gap-analysis"}',
  '{"inputs": {"domain": "string", "competitors": "array?"}, "outputs": {"topicGaps": "array", "semanticGaps": "array", "formatGaps": "object", "freshnessGaps": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/gap-analyzer',
  '{"maxTopics": 100, "semanticAnalysis": true}',
  ARRAY['content-gap', 'opportunity', 'competitor-analysis', 'topics'],
  true,
  true,
  false,
  9000,
  0,
  5000,
  2.2,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'content-optimizer-ai_v1',
  '1.0.0',
  'seo',
  'AI-powered content optimization for engagement and SEO',
  'Intelagent',
  '{"category": "content", "ai_model": "gpt-4"}',
  '{"inputs": {"content": "string", "targetKeywords": "array?"}, "outputs": {"readability": "object", "engagement": "object", "seoOptimization": "object", "aiRewrite": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/content-optimizer',
  '{"maxLength": 10000, "tones": ["professional", "casual", "technical"]}',
  ARRAY['content', 'optimization', 'ai-writing', 'readability', 'engagement'],
  true,
  true,
  false,
  12000,
  1500,
  4000,
  2.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'content-cannibalization-detector_v1',
  '1.0.0',
  'seo',
  'Identify and resolve content cannibalization issues',
  'Intelagent',
  '{"category": "content", "detection_method": "semantic-similarity"}',
  '{"inputs": {"domain": "string", "keywords": "array?"}, "outputs": {"clusters": "array", "resolutionPlan": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/cannibalization-detector',
  '{"similarityThreshold": 0.7, "minOverlap": 3}',
  ARRAY['cannibalization', 'duplicate-content', 'consolidation', 'internal-competition'],
  true,
  true,
  false,
  7000,
  0,
  4000,
  1.8,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

-- Monitoring & Analytics Skills
(
  gen_random_uuid(),
  'serp-monitor_v1',
  '1.0.0',
  'seo',
  'Monitor SERP features and ranking changes',
  'Intelagent',
  '{"category": "monitoring", "features": ["featured-snippets", "paa", "knowledge-panels", "local-pack"]}',
  '{"inputs": {"keywords": "array", "domain": "string"}, "outputs": {"rankings": "object", "serpFeatures": "object", "volatility": "object", "opportunities": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/serp-monitor',
  '{"updateFrequency": "daily", "historicalData": 90}',
  ARRAY['serp', 'rankings', 'monitoring', 'featured-snippets', 'serp-features'],
  true,
  true,
  false,
  10000,
  0,
  5000,
  2.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'ai-search-visibility-tracker_v1',
  '1.0.0',
  'seo',
  'Track visibility in AI search systems',
  'Intelagent',
  '{"category": "monitoring", "ai_systems": ["chatgpt", "perplexity", "claude", "bard", "bing-chat"]}',
  '{"inputs": {"domain": "string", "aiSystems": "array?"}, "outputs": {"visibilityScores": "object", "contentPerformance": "array", "competitiveAnalysis": "object", "optimizationOpportunities": "array"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/ai-visibility-tracker',
  '{"trackingFrequency": "weekly", "citationAnalysis": true}',
  ARRAY['ai-visibility', 'chatgpt', 'perplexity', 'monitoring', 'citations'],
  true,
  true,
  false,
  15000,
  0,
  8000,
  3.0,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
),

(
  gen_random_uuid(),
  'conversion-optimizer_v1',
  '1.0.0',
  'seo',
  'Optimize for conversions from organic traffic',
  'Intelagent',
  '{"category": "conversion", "optimization_methods": ["ab-testing", "funnel-analysis", "heatmaps"]}',
  '{"inputs": {"url": "string", "goals": "array?"}, "outputs": {"funnelAnalysis": "object", "croRecommendations": "array", "landingPageOptimization": "object", "userIntentAlignment": "object"}}',
  '{"tier": "Pro", "minLicenseLevel": "Pro"}',
  'internal_service',
  'skills-orchestrator/seo/conversion-optimizer',
  '{"testingFramework": "optimizely", "heatmapProvider": "hotjar"}',
  ARRAY['cro', 'conversion', 'funnel', 'optimization', 'landing-pages'],
  true,
  true,
  false,
  10000,
  0,
  4000,
  2.5,
  'pro',
  ARRAY['all'],
  ARRAY[],
  NOW(),
  NOW()
)

ON CONFLICT (name, version) DO UPDATE SET
  description = EXCLUDED.description,
  metadata = EXCLUDED.metadata,
  contract = EXCLUDED.contract,
  configuration = EXCLUDED.configuration,
  tags = EXCLUDED.tags,
  base_cost_pence = EXCLUDED.base_cost_pence,
  skill_tier = EXCLUDED.skill_tier,
  updated_at = NOW();