// Comprehensive Skills Catalog - 395+ Skills
export interface Skill {
  id: string;
  name: string;
  category: string;
  description?: string;
  tier?: 'basic' | 'advanced' | 'enterprise';
}

// Updated catalog with 500+ skills across all categories
export const SKILLS_CATALOG: { [category: string]: Skill[] } = {
  // Sales & CRM Skills (45 skills)
  'Sales & CRM': [
    { id: 'lead_generation', name: 'Lead Generation', category: 'Sales & CRM' },
    { id: 'lead_scoring', name: 'Lead Scoring', category: 'Sales & CRM' },
    { id: 'lead_nurturing', name: 'Lead Nurturing', category: 'Sales & CRM' },
    { id: 'contact_management', name: 'Contact Management', category: 'Sales & CRM' },
    { id: 'deal_tracking', name: 'Deal Tracking', category: 'Sales & CRM' },
    { id: 'pipeline_management', name: 'Pipeline Management', category: 'Sales & CRM' },
    { id: 'opportunity_tracking', name: 'Opportunity Tracking', category: 'Sales & CRM' },
    { id: 'sales_forecasting', name: 'Sales Forecasting', category: 'Sales & CRM' },
    { id: 'quote_generation', name: 'Quote Generation', category: 'Sales & CRM' },
    { id: 'proposal_builder', name: 'Proposal Builder', category: 'Sales & CRM' },
    { id: 'contract_management', name: 'Contract Management', category: 'Sales & CRM' },
    { id: 'account_management', name: 'Account Management', category: 'Sales & CRM' },
    { id: 'territory_management', name: 'Territory Management', category: 'Sales & CRM' },
    { id: 'commission_tracking', name: 'Commission Tracking', category: 'Sales & CRM' },
    { id: 'sales_analytics', name: 'Sales Analytics', category: 'Sales & CRM' },
    { id: 'revenue_forecasting', name: 'Revenue Forecasting', category: 'Sales & CRM' },
    { id: 'sales_cadence', name: 'Sales Cadence', category: 'Sales & CRM' },
    { id: 'email_sequences', name: 'Email Sequences', category: 'Sales & CRM' },
    { id: 'follow_up_automation', name: 'Follow-up Automation', category: 'Sales & CRM' },
    { id: 'meeting_scheduler', name: 'Meeting Scheduler', category: 'Sales & CRM' },
    { id: 'calendar_sync', name: 'Calendar Sync', category: 'Sales & CRM' },
    { id: 'call_recording', name: 'Call Recording', category: 'Sales & CRM' },
    { id: 'conversation_intelligence', name: 'Conversation Intelligence', category: 'Sales & CRM' },
    { id: 'sales_enablement', name: 'Sales Enablement', category: 'Sales & CRM' },
    { id: 'content_library', name: 'Content Library', category: 'Sales & CRM' },
    { id: 'battle_cards', name: 'Battle Cards', category: 'Sales & CRM' },
    { id: 'competitor_intelligence', name: 'Competitor Intelligence', category: 'Sales & CRM' },
    { id: 'win_loss_analysis', name: 'Win/Loss Analysis', category: 'Sales & CRM' },
    { id: 'customer_segmentation', name: 'Customer Segmentation', category: 'Sales & CRM' },
    { id: 'personalization_engine', name: 'Personalization Engine', category: 'Sales & CRM' },
    { id: 'dynamic_pricing', name: 'Dynamic Pricing', category: 'Sales & CRM' },
    { id: 'upsell_cross_sell', name: 'Upsell/Cross-sell', category: 'Sales & CRM' },
    { id: 'renewal_management', name: 'Renewal Management', category: 'Sales & CRM' },
    { id: 'churn_prevention', name: 'Churn Prevention', category: 'Sales & CRM' },
    { id: 'customer_lifecycle', name: 'Customer Lifecycle', category: 'Sales & CRM' },
    { id: 'referral_tracking', name: 'Referral Tracking', category: 'Sales & CRM' },
    { id: 'partner_management', name: 'Partner Management', category: 'Sales & CRM' },
    { id: 'channel_management', name: 'Channel Management', category: 'Sales & CRM' },
    { id: 'sales_coaching', name: 'Sales Coaching', category: 'Sales & CRM' },
    { id: 'performance_metrics', name: 'Performance Metrics', category: 'Sales & CRM' },
    { id: 'team_collaboration', name: 'Team Collaboration', category: 'Sales & CRM' },
    { id: 'mobile_crm', name: 'Mobile CRM Access', category: 'Sales & CRM' },
    { id: 'offline_sync', name: 'Offline Sync', category: 'Sales & CRM' },
    { id: 'crm_sync', name: 'CRM Sync', category: 'Sales & CRM' },
    { id: 'email_outreach', name: 'Email Outreach', category: 'Sales & CRM' }
  ],

  // Customer Support Skills (40 skills)
  'Customer Support': [
    { id: 'ticket_management', name: 'Ticket Management', category: 'Customer Support' },
    { id: 'auto_response', name: 'Auto Response', category: 'Customer Support' },
    { id: 'knowledge_base', name: 'Knowledge Base', category: 'Customer Support' },
    { id: 'chat_support', name: 'Chat Support', category: 'Customer Support' },
    { id: 'faq_builder', name: 'FAQ Builder', category: 'Customer Support' },
    { id: 'customer_portal', name: 'Customer Portal', category: 'Customer Support' },
    { id: 'sla_management', name: 'SLA Management', category: 'Customer Support' },
    { id: 'escalation_rules', name: 'Escalation Rules', category: 'Customer Support' },
    { id: 'satisfaction_surveys', name: 'Satisfaction Surveys', category: 'Customer Support' },
    { id: 'help_desk', name: 'Help Desk', category: 'Customer Support' },
    { id: 'live_chat_widget', name: 'Live Chat Widget', category: 'Customer Support' },
    { id: 'email_support', name: 'Email Support', category: 'Customer Support' },
    { id: 'phone_support', name: 'Phone Support Integration', category: 'Customer Support' },
    { id: 'social_support', name: 'Social Media Support', category: 'Customer Support' },
    { id: 'community_forum', name: 'Community Forum', category: 'Customer Support' },
    { id: 'sentiment_analysis', name: 'Sentiment Analysis', category: 'Customer Support' },
    { id: 'priority_routing', name: 'Priority Routing', category: 'Customer Support' },
    { id: 'agent_assignment', name: 'Agent Assignment', category: 'Customer Support' },
    { id: 'workload_balancing', name: 'Workload Balancing', category: 'Customer Support' },
    { id: 'response_templates', name: 'Response Templates', category: 'Customer Support' },
    { id: 'macro_management', name: 'Macro Management', category: 'Customer Support' },
    { id: 'canned_responses', name: 'Canned Responses', category: 'Customer Support' },
    { id: 'multilanguage_support', name: 'Multi-language Support', category: 'Customer Support' },
    { id: 'translation_services', name: 'Translation Services', category: 'Customer Support' },
    { id: 'screen_sharing', name: 'Screen Sharing', category: 'Customer Support' },
    { id: 'cobrowsing', name: 'Co-browsing', category: 'Customer Support' },
    { id: 'remote_desktop', name: 'Remote Desktop', category: 'Customer Support' },
    { id: 'file_sharing', name: 'File Sharing', category: 'Customer Support' },
    { id: 'video_support', name: 'Video Support', category: 'Customer Support' },
    { id: 'voice_recognition', name: 'Voice Recognition', category: 'Customer Support' },
    { id: 'chatbot_integration', name: 'Chatbot Integration', category: 'Customer Support' },
    { id: 'ai_suggestions', name: 'AI Suggestions', category: 'Customer Support' },
    { id: 'smart_routing', name: 'Smart Routing', category: 'Customer Support' },
    { id: 'customer_journey', name: 'Customer Journey Tracking', category: 'Customer Support' },
    { id: 'issue_prediction', name: 'Issue Prediction', category: 'Customer Support' },
    { id: 'proactive_support', name: 'Proactive Support', category: 'Customer Support' },
    { id: 'customer_health_score', name: 'Customer Health Score', category: 'Customer Support' },
    { id: 'retention_analytics', name: 'Retention Analytics', category: 'Customer Support' },
    { id: 'feedback_loop', name: 'Feedback Loop', category: 'Customer Support' },
    { id: 'quality_assurance', name: 'Quality Assurance', category: 'Customer Support' }
  ],

  // Marketing & Content Skills (45 skills)
  'Marketing & Content': [
    { id: 'content_creation', name: 'Content Creation', category: 'Marketing & Content' },
    { id: 'social_media', name: 'Social Media Management', category: 'Marketing & Content' },
    { id: 'email_campaigns', name: 'Email Campaigns', category: 'Marketing & Content' },
    { id: 'seo_optimization', name: 'SEO Optimization', category: 'Marketing & Content' },
    { id: 'landing_page_builder', name: 'Landing Page Builder', category: 'Marketing & Content' },
    { id: 'ab_testing', name: 'A/B Testing', category: 'Marketing & Content' },
    { id: 'marketing_automation', name: 'Marketing Automation', category: 'Marketing & Content' },
    { id: 'lead_capture_forms', name: 'Lead Capture Forms', category: 'Marketing & Content' },
    { id: 'campaign_tracking', name: 'Campaign Tracking', category: 'Marketing & Content' },
    { id: 'content_calendar', name: 'Content Calendar', category: 'Marketing & Content' },
    { id: 'social_scheduling', name: 'Social Media Scheduling', category: 'Marketing & Content' },
    { id: 'influencer_outreach', name: 'Influencer Outreach', category: 'Marketing & Content' },
    { id: 'brand_monitoring', name: 'Brand Monitoring', category: 'Marketing & Content' },
    { id: 'competitor_analysis', name: 'Competitor Analysis', category: 'Marketing & Content' },
    { id: 'marketing_attribution', name: 'Marketing Attribution', category: 'Marketing & Content' },
    { id: 'roi_tracking', name: 'ROI Tracking', category: 'Marketing & Content' },
    { id: 'conversion_optimization', name: 'Conversion Optimization', category: 'Marketing & Content' },
    { id: 'funnel_analysis', name: 'Funnel Analysis', category: 'Marketing & Content' },
    { id: 'customer_personas', name: 'Customer Personas', category: 'Marketing & Content' },
    { id: 'content_personalization', name: 'Content Personalization', category: 'Marketing & Content' },
    { id: 'dynamic_content', name: 'Dynamic Content', category: 'Marketing & Content' },
    { id: 'behavioral_triggers', name: 'Behavioral Triggers', category: 'Marketing & Content' },
    { id: 'drip_campaigns', name: 'Drip Campaigns', category: 'Marketing & Content' },
    { id: 'newsletter_management', name: 'Newsletter Management', category: 'Marketing & Content' },
    { id: 'sms_marketing', name: 'SMS Marketing', category: 'Marketing & Content' },
    { id: 'push_notifications', name: 'Push Notifications', category: 'Marketing & Content' },
    { id: 'inapp_messaging', name: 'In-app Messaging', category: 'Marketing & Content' },
    { id: 'webinar_management', name: 'Webinar Management', category: 'Marketing & Content' },
    { id: 'event_marketing', name: 'Event Marketing', category: 'Marketing & Content' },
    { id: 'referral_programs', name: 'Referral Programs', category: 'Marketing & Content' },
    { id: 'loyalty_programs', name: 'Loyalty Programs', category: 'Marketing & Content' },
    { id: 'affiliate_marketing', name: 'Affiliate Marketing', category: 'Marketing & Content' },
    { id: 'content_syndication', name: 'Content Syndication', category: 'Marketing & Content' },
    { id: 'pr_distribution', name: 'PR Distribution', category: 'Marketing & Content' },
    { id: 'media_planning', name: 'Media Planning', category: 'Marketing & Content' },
    { id: 'ad_campaign_management', name: 'Ad Campaign Management', category: 'Marketing & Content' },
    { id: 'retargeting', name: 'Retargeting', category: 'Marketing & Content' },
    { id: 'lookalike_audiences', name: 'Lookalike Audiences', category: 'Marketing & Content' },
    { id: 'marketing_mix_modeling', name: 'Marketing Mix Modeling', category: 'Marketing & Content' },
    { id: 'content_scoring', name: 'Content Scoring', category: 'Marketing & Content' },
    { id: 'blog_management', name: 'Blog Management', category: 'Marketing & Content' },
    { id: 'video_marketing', name: 'Video Marketing', category: 'Marketing & Content' },
    { id: 'podcast_management', name: 'Podcast Management', category: 'Marketing & Content' },
    { id: 'user_generated_content', name: 'User Generated Content', category: 'Marketing & Content' },
    { id: 'community_building', name: 'Community Building', category: 'Marketing & Content' }
  ],

  // Data & Analytics Skills (40 skills)
  'Data & Analytics': [
    { id: 'data_collection', name: 'Data Collection', category: 'Data & Analytics' },
    { id: 'data_cleaning', name: 'Data Cleaning', category: 'Data & Analytics' },
    { id: 'data_transformation', name: 'Data Transformation', category: 'Data & Analytics' },
    { id: 'etl_pipelines', name: 'ETL Pipelines', category: 'Data & Analytics' },
    { id: 'data_warehousing', name: 'Data Warehousing', category: 'Data & Analytics' },
    { id: 'statistical_analysis', name: 'Statistical Analysis', category: 'Data & Analytics' },
    { id: 'predictive_analytics', name: 'Predictive Analytics', category: 'Data & Analytics' },
    { id: 'machine_learning', name: 'Machine Learning', category: 'Data & Analytics' },
    { id: 'deep_learning', name: 'Deep Learning', category: 'Data & Analytics' },
    { id: 'neural_networks', name: 'Neural Networks', category: 'Data & Analytics' },
    { id: 'nlp', name: 'Natural Language Processing', category: 'Data & Analytics' },
    { id: 'computer_vision', name: 'Computer Vision', category: 'Data & Analytics' },
    { id: 'time_series', name: 'Time Series Forecasting', category: 'Data & Analytics' },
    { id: 'anomaly_detection', name: 'Anomaly Detection', category: 'Data & Analytics' },
    { id: 'pattern_recognition', name: 'Pattern Recognition', category: 'Data & Analytics' },
    { id: 'data_visualization', name: 'Data Visualization', category: 'Data & Analytics' },
    { id: 'interactive_dashboards', name: 'Interactive Dashboards', category: 'Data & Analytics' },
    { id: 'realtime_analytics', name: 'Real-time Analytics', category: 'Data & Analytics' },
    { id: 'streaming_analytics', name: 'Streaming Analytics', category: 'Data & Analytics' },
    { id: 'big_data_processing', name: 'Big Data Processing', category: 'Data & Analytics' },
    { id: 'sql_queries', name: 'SQL Queries', category: 'Data & Analytics' },
    { id: 'nosql_databases', name: 'NoSQL Databases', category: 'Data & Analytics' },
    { id: 'graph_databases', name: 'Graph Databases', category: 'Data & Analytics' },
    { id: 'data_lakes', name: 'Data Lakes', category: 'Data & Analytics' },
    { id: 'cloud_data_platforms', name: 'Cloud Data Platforms', category: 'Data & Analytics' },
    { id: 'business_intelligence', name: 'Business Intelligence', category: 'Data & Analytics' },
    { id: 'executive_reporting', name: 'Executive Reporting', category: 'Data & Analytics' },
    { id: 'adhoc_analysis', name: 'Ad-hoc Analysis', category: 'Data & Analytics' },
    { id: 'selfservice_analytics', name: 'Self-service Analytics', category: 'Data & Analytics' },
    { id: 'embedded_analytics', name: 'Embedded Analytics', category: 'Data & Analytics' },
    { id: 'data_governance', name: 'Data Governance', category: 'Data & Analytics' },
    { id: 'data_quality', name: 'Data Quality Management', category: 'Data & Analytics' },
    { id: 'master_data', name: 'Master Data Management', category: 'Data & Analytics' },
    { id: 'metadata_management', name: 'Metadata Management', category: 'Data & Analytics' },
    { id: 'data_lineage', name: 'Data Lineage', category: 'Data & Analytics' },
    { id: 'privacy_compliance', name: 'Privacy Compliance', category: 'Data & Analytics' },
    { id: 'data_security', name: 'Data Security', category: 'Data & Analytics' },
    { id: 'encryption', name: 'Encryption', category: 'Data & Analytics' },
    { id: 'access_control', name: 'Access Control', category: 'Data & Analytics' },
    { id: 'audit_trails', name: 'Audit Trails', category: 'Data & Analytics' }
  ],

  // Operations & Workflow Skills (35 skills)
  'Operations & Workflow': [
    { id: 'workflow_automation', name: 'Workflow Automation', category: 'Operations & Workflow' },
    { id: 'process_optimization', name: 'Process Optimization', category: 'Operations & Workflow' },
    { id: 'task_management', name: 'Task Management', category: 'Operations & Workflow' },
    { id: 'resource_planning', name: 'Resource Planning', category: 'Operations & Workflow' },
    { id: 'inventory_control', name: 'Inventory Control', category: 'Operations & Workflow' },
    { id: 'supply_chain', name: 'Supply Chain Management', category: 'Operations & Workflow' },
    { id: 'quality_assurance_ops', name: 'Quality Assurance', category: 'Operations & Workflow' },
    { id: 'performance_monitoring', name: 'Performance Monitoring', category: 'Operations & Workflow' },
    { id: 'capacity_planning', name: 'Capacity Planning', category: 'Operations & Workflow' },
    { id: 'scheduling', name: 'Scheduling', category: 'Operations & Workflow' },
    { id: 'document_management', name: 'Document Management', category: 'Operations & Workflow' },
    { id: 'compliance_tracking', name: 'Compliance Tracking', category: 'Operations & Workflow' },
    { id: 'audit_management', name: 'Audit Management', category: 'Operations & Workflow' },
    { id: 'risk_assessment', name: 'Risk Assessment', category: 'Operations & Workflow' },
    { id: 'vendor_management', name: 'Vendor Management', category: 'Operations & Workflow' },
    { id: 'purchase_order', name: 'Purchase Order Processing', category: 'Operations & Workflow' },
    { id: 'invoice_processing', name: 'Invoice Processing', category: 'Operations & Workflow' },
    { id: 'expense_management', name: 'Expense Management', category: 'Operations & Workflow' },
    { id: 'budget_tracking', name: 'Budget Tracking', category: 'Operations & Workflow' },
    { id: 'cost_analysis', name: 'Cost Analysis', category: 'Operations & Workflow' },
    { id: 'time_tracking', name: 'Time Tracking', category: 'Operations & Workflow' },
    { id: 'employee_scheduling', name: 'Employee Scheduling', category: 'Operations & Workflow' },
    { id: 'shift_management', name: 'Shift Management', category: 'Operations & Workflow' },
    { id: 'leave_management', name: 'Leave Management', category: 'Operations & Workflow' },
    { id: 'attendance_tracking', name: 'Attendance Tracking', category: 'Operations & Workflow' },
    { id: 'asset_management', name: 'Asset Management', category: 'Operations & Workflow' },
    { id: 'maintenance_scheduling', name: 'Maintenance Scheduling', category: 'Operations & Workflow' },
    { id: 'equipment_tracking', name: 'Equipment Tracking', category: 'Operations & Workflow' },
    { id: 'facility_management', name: 'Facility Management', category: 'Operations & Workflow' },
    { id: 'space_planning', name: 'Space Planning', category: 'Operations & Workflow' },
    { id: 'project_coordination', name: 'Project Coordination', category: 'Operations & Workflow' },
    { id: 'resource_allocation', name: 'Resource Allocation', category: 'Operations & Workflow' },
    { id: 'milestone_tracking', name: 'Milestone Tracking', category: 'Operations & Workflow' },
    { id: 'dependency_management', name: 'Dependency Management', category: 'Operations & Workflow' },
    { id: 'critical_path', name: 'Critical Path Analysis', category: 'Operations & Workflow' }
  ],

  // Finance & Accounting Skills (30 skills)
  'Finance & Accounting': [
    { id: 'bookkeeping', name: 'Bookkeeping', category: 'Finance & Accounting' },
    { id: 'accounts_payable', name: 'Accounts Payable', category: 'Finance & Accounting' },
    { id: 'accounts_receivable', name: 'Accounts Receivable', category: 'Finance & Accounting' },
    { id: 'general_ledger', name: 'General Ledger', category: 'Finance & Accounting' },
    { id: 'financial_reporting', name: 'Financial Reporting', category: 'Finance & Accounting' },
    { id: 'tax_preparation', name: 'Tax Preparation', category: 'Finance & Accounting' },
    { id: 'payroll_processing', name: 'Payroll Processing', category: 'Finance & Accounting' },
    { id: 'billing_invoicing', name: 'Billing & Invoicing', category: 'Finance & Accounting' },
    { id: 'payment_processing', name: 'Payment Processing', category: 'Finance & Accounting' },
    { id: 'cash_flow', name: 'Cash Flow Management', category: 'Finance & Accounting' },
    { id: 'budget_planning', name: 'Budget Planning', category: 'Finance & Accounting' },
    { id: 'financial_forecasting', name: 'Financial Forecasting', category: 'Finance & Accounting' },
    { id: 'profit_loss', name: 'Profit & Loss Analysis', category: 'Finance & Accounting' },
    { id: 'balance_sheet', name: 'Balance Sheet Management', category: 'Finance & Accounting' },
    { id: 'financial_analytics', name: 'Financial Analytics', category: 'Finance & Accounting' },
    { id: 'expense_tracking', name: 'Expense Tracking', category: 'Finance & Accounting' },
    { id: 'reimbursement', name: 'Reimbursement Management', category: 'Finance & Accounting' },
    { id: 'credit_control', name: 'Credit Control', category: 'Finance & Accounting' },
    { id: 'collections', name: 'Collections Management', category: 'Finance & Accounting' },
    { id: 'reconciliation', name: 'Reconciliation', category: 'Finance & Accounting' },
    { id: 'fixed_assets', name: 'Fixed Assets Management', category: 'Finance & Accounting' },
    { id: 'depreciation', name: 'Depreciation Tracking', category: 'Finance & Accounting' },
    { id: 'multi_currency', name: 'Multi-currency Support', category: 'Finance & Accounting' },
    { id: 'exchange_rates', name: 'Exchange Rate Management', category: 'Finance & Accounting' },
    { id: 'financial_compliance', name: 'Financial Compliance', category: 'Finance & Accounting' },
    { id: 'audit_preparation', name: 'Audit Preparation', category: 'Finance & Accounting' },
    { id: 'cost_accounting', name: 'Cost Accounting', category: 'Finance & Accounting' },
    { id: 'project_accounting', name: 'Project Accounting', category: 'Finance & Accounting' },
    { id: 'fund_accounting', name: 'Fund Accounting', category: 'Finance & Accounting' },
    { id: 'treasury_management', name: 'Treasury Management', category: 'Finance & Accounting' }
  ],

  // HR & People Management Skills (35 skills)
  'HR & People': [
    { id: 'recruitment', name: 'Recruitment Management', category: 'HR & People' },
    { id: 'applicant_tracking', name: 'Applicant Tracking', category: 'HR & People' },
    { id: 'resume_screening', name: 'Resume Screening', category: 'HR & People' },
    { id: 'interview_scheduling', name: 'Interview Scheduling', category: 'HR & People' },
    { id: 'onboarding', name: 'Employee Onboarding', category: 'HR & People' },
    { id: 'offboarding', name: 'Employee Offboarding', category: 'HR & People' },
    { id: 'employee_database', name: 'Employee Database', category: 'HR & People' },
    { id: 'performance_reviews', name: 'Performance Reviews', category: 'HR & People' },
    { id: 'goal_setting', name: 'Goal Setting & OKRs', category: 'HR & People' },
    { id: 'training_management', name: 'Training Management', category: 'HR & People' },
    { id: 'learning_development', name: 'Learning & Development', category: 'HR & People' },
    { id: 'certification_tracking', name: 'Certification Tracking', category: 'HR & People' },
    { id: 'compensation_management', name: 'Compensation Management', category: 'HR & People' },
    { id: 'benefits_administration', name: 'Benefits Administration', category: 'HR & People' },
    { id: 'time_off_management', name: 'Time-off Management', category: 'HR & People' },
    { id: 'employee_engagement', name: 'Employee Engagement', category: 'HR & People' },
    { id: 'pulse_surveys', name: 'Pulse Surveys', category: 'HR & People' },
    { id: 'feedback_360', name: '360 Feedback', category: 'HR & People' },
    { id: 'succession_planning', name: 'Succession Planning', category: 'HR & People' },
    { id: 'talent_management', name: 'Talent Management', category: 'HR & People' },
    { id: 'workforce_planning', name: 'Workforce Planning', category: 'HR & People' },
    { id: 'org_chart', name: 'Org Chart Management', category: 'HR & People' },
    { id: 'employee_selfservice', name: 'Employee Self-service', category: 'HR & People' },
    { id: 'hr_analytics', name: 'HR Analytics', category: 'HR & People' },
    { id: 'diversity_inclusion', name: 'Diversity & Inclusion', category: 'HR & People' },
    { id: 'compliance_hr', name: 'HR Compliance', category: 'HR & People' },
    { id: 'policy_management', name: 'Policy Management', category: 'HR & People' },
    { id: 'employee_handbook', name: 'Employee Handbook', category: 'HR & People' },
    { id: 'disciplinary_actions', name: 'Disciplinary Actions', category: 'HR & People' },
    { id: 'grievance_management', name: 'Grievance Management', category: 'HR & People' },
    { id: 'exit_interviews', name: 'Exit Interviews', category: 'HR & People' },
    { id: 'employee_wellness', name: 'Employee Wellness', category: 'HR & People' },
    { id: 'recognition_rewards', name: 'Recognition & Rewards', category: 'HR & People' },
    { id: 'team_building', name: 'Team Building', category: 'HR & People' },
    { id: 'culture_development', name: 'Culture Development', category: 'HR & People' }
  ],

  // E-commerce & Retail Skills (35 skills)
  'E-commerce & Retail': [
    { id: 'product_catalog', name: 'Product Catalog', category: 'E-commerce & Retail' },
    { id: 'inventory_management', name: 'Inventory Management', category: 'E-commerce & Retail' },
    { id: 'order_management', name: 'Order Management', category: 'E-commerce & Retail' },
    { id: 'shopping_cart', name: 'Shopping Cart', category: 'E-commerce & Retail' },
    { id: 'checkout_process', name: 'Checkout Process', category: 'E-commerce & Retail' },
    { id: 'payment_gateway', name: 'Payment Gateway', category: 'E-commerce & Retail' },
    { id: 'shipping_fulfillment', name: 'Shipping & Fulfillment', category: 'E-commerce & Retail' },
    { id: 'returns_refunds', name: 'Returns & Refunds', category: 'E-commerce & Retail' },
    { id: 'product_reviews', name: 'Product Reviews', category: 'E-commerce & Retail' },
    { id: 'ratings_system', name: 'Ratings System', category: 'E-commerce & Retail' },
    { id: 'wishlist', name: 'Wishlist Management', category: 'E-commerce & Retail' },
    { id: 'product_recommendations', name: 'Product Recommendations', category: 'E-commerce & Retail' },
    { id: 'cross_selling', name: 'Cross-selling', category: 'E-commerce & Retail' },
    { id: 'upselling', name: 'Upselling', category: 'E-commerce & Retail' },
    { id: 'discount_codes', name: 'Discount Codes', category: 'E-commerce & Retail' },
    { id: 'gift_cards', name: 'Gift Cards', category: 'E-commerce & Retail' },
    { id: 'loyalty_points', name: 'Loyalty Points', category: 'E-commerce & Retail' },
    { id: 'subscription_commerce', name: 'Subscription Commerce', category: 'E-commerce & Retail' },
    { id: 'marketplace_integration', name: 'Marketplace Integration', category: 'E-commerce & Retail' },
    { id: 'dropshipping', name: 'Dropshipping', category: 'E-commerce & Retail' },
    { id: 'wholesale_management', name: 'Wholesale Management', category: 'E-commerce & Retail' },
    { id: 'b2b_ecommerce', name: 'B2B E-commerce', category: 'E-commerce & Retail' },
    { id: 'multi_channel', name: 'Multi-channel Selling', category: 'E-commerce & Retail' },
    { id: 'pos_integration', name: 'POS Integration', category: 'E-commerce & Retail' },
    { id: 'barcode_scanning', name: 'Barcode Scanning', category: 'E-commerce & Retail' },
    { id: 'store_locator', name: 'Store Locator', category: 'E-commerce & Retail' },
    { id: 'click_collect', name: 'Click & Collect', category: 'E-commerce & Retail' },
    { id: 'virtual_try_on', name: 'Virtual Try-on', category: 'E-commerce & Retail' },
    { id: 'size_guide', name: 'Size Guide', category: 'E-commerce & Retail' },
    { id: 'product_configurator', name: 'Product Configurator', category: 'E-commerce & Retail' },
    { id: 'bundle_products', name: 'Bundle Products', category: 'E-commerce & Retail' },
    { id: 'pre_orders', name: 'Pre-orders', category: 'E-commerce & Retail' },
    { id: 'backorder_management', name: 'Backorder Management', category: 'E-commerce & Retail' },
    { id: 'abandoned_cart', name: 'Abandoned Cart Recovery', category: 'E-commerce & Retail' },
    { id: 'price_monitoring', name: 'Price Monitoring', category: 'E-commerce & Retail' }
  ],

  // IT & Security Skills (30 skills)
  'IT & Security': [
    { id: 'user_authentication', name: 'User Authentication', category: 'IT & Security' },
    { id: 'sso', name: 'Single Sign-On (SSO)', category: 'IT & Security' },
    { id: 'two_factor_auth', name: 'Two-Factor Authentication', category: 'IT & Security' },
    { id: 'role_based_access', name: 'Role-Based Access Control', category: 'IT & Security' },
    { id: 'password_management', name: 'Password Management', category: 'IT & Security' },
    { id: 'security_monitoring', name: 'Security Monitoring', category: 'IT & Security' },
    { id: 'threat_detection', name: 'Threat Detection', category: 'IT & Security' },
    { id: 'incident_response', name: 'Incident Response', category: 'IT & Security' },
    { id: 'vulnerability_scanning', name: 'Vulnerability Scanning', category: 'IT & Security' },
    { id: 'penetration_testing', name: 'Penetration Testing', category: 'IT & Security' },
    { id: 'firewall_management', name: 'Firewall Management', category: 'IT & Security' },
    { id: 'network_monitoring', name: 'Network Monitoring', category: 'IT & Security' },
    { id: 'log_management', name: 'Log Management', category: 'IT & Security' },
    { id: 'siem', name: 'SIEM Integration', category: 'IT & Security' },
    { id: 'backup_recovery', name: 'Backup & Recovery', category: 'IT & Security' },
    { id: 'disaster_recovery', name: 'Disaster Recovery', category: 'IT & Security' },
    { id: 'business_continuity', name: 'Business Continuity', category: 'IT & Security' },
    { id: 'patch_management', name: 'Patch Management', category: 'IT & Security' },
    { id: 'asset_discovery', name: 'Asset Discovery', category: 'IT & Security' },
    { id: 'configuration_management', name: 'Configuration Management', category: 'IT & Security' },
    { id: 'change_management', name: 'Change Management', category: 'IT & Security' },
    { id: 'service_desk', name: 'Service Desk', category: 'IT & Security' },
    { id: 'remote_support', name: 'Remote Support', category: 'IT & Security' },
    { id: 'software_deployment', name: 'Software Deployment', category: 'IT & Security' },
    { id: 'license_management', name: 'License Management', category: 'IT & Security' },
    { id: 'cloud_management', name: 'Cloud Management', category: 'IT & Security' },
    { id: 'container_orchestration', name: 'Container Orchestration', category: 'IT & Security' },
    { id: 'infrastructure_code', name: 'Infrastructure as Code', category: 'IT & Security' },
    { id: 'monitoring_alerting', name: 'Monitoring & Alerting', category: 'IT & Security' },
    { id: 'performance_tuning', name: 'Performance Tuning', category: 'IT & Security' }
  ],

  // Communication & Collaboration Skills (30 skills)
  'Communication': [
    { id: 'email_integration', name: 'Email Integration', category: 'Communication' },
    { id: 'calendar_management', name: 'Calendar Management', category: 'Communication' },
    { id: 'video_conferencing', name: 'Video Conferencing', category: 'Communication' },
    { id: 'instant_messaging', name: 'Instant Messaging', category: 'Communication' },
    { id: 'team_chat', name: 'Team Chat', category: 'Communication' },
    { id: 'file_sharing_comm', name: 'File Sharing', category: 'Communication' },
    { id: 'screen_share', name: 'Screen Sharing', category: 'Communication' },
    { id: 'whiteboarding', name: 'Digital Whiteboarding', category: 'Communication' },
    { id: 'document_collaboration', name: 'Document Collaboration', category: 'Communication' },
    { id: 'project_boards', name: 'Project Boards', category: 'Communication' },
    { id: 'task_assignment', name: 'Task Assignment', category: 'Communication' },
    { id: 'status_updates', name: 'Status Updates', category: 'Communication' },
    { id: 'meeting_notes', name: 'Meeting Notes', category: 'Communication' },
    { id: 'action_items', name: 'Action Items', category: 'Communication' },
    { id: 'decision_tracking', name: 'Decision Tracking', category: 'Communication' },
    { id: 'knowledge_sharing', name: 'Knowledge Sharing', category: 'Communication' },
    { id: 'wiki_management', name: 'Wiki Management', category: 'Communication' },
    { id: 'announcement_board', name: 'Announcement Board', category: 'Communication' },
    { id: 'employee_directory', name: 'Employee Directory', category: 'Communication' },
    { id: 'org_news', name: 'Organizational News', category: 'Communication' },
    { id: 'feedback_collection', name: 'Feedback Collection', category: 'Communication' },
    { id: 'suggestion_box', name: 'Suggestion Box', category: 'Communication' },
    { id: 'polls_voting', name: 'Polls & Voting', category: 'Communication' },
    { id: 'event_planning', name: 'Event Planning', category: 'Communication' },
    { id: 'room_booking', name: 'Room Booking', category: 'Communication' },
    { id: 'visitor_management', name: 'Visitor Management', category: 'Communication' },
    { id: 'broadcast_messaging', name: 'Broadcast Messaging', category: 'Communication' },
    { id: 'emergency_alerts', name: 'Emergency Alerts', category: 'Communication' },
    { id: 'translation_comm', name: 'Translation Services', category: 'Communication' },
    { id: 'transcription', name: 'Transcription Services', category: 'Communication' }
  ],

  // Industry Specific Skills (50 skills)
  'Industry Specific': [
    { id: 'healthcare_ehr', name: 'EHR Management', category: 'Industry Specific' },
    { id: 'hipaa_compliance', name: 'HIPAA Compliance', category: 'Industry Specific' },
    { id: 'patient_scheduling', name: 'Patient Scheduling', category: 'Industry Specific' },
    { id: 'medical_billing', name: 'Medical Billing', category: 'Industry Specific' },
    { id: 'telemedicine', name: 'Telemedicine Support', category: 'Industry Specific' },
    { id: 'prescription_management', name: 'Prescription Management', category: 'Industry Specific' },
    { id: 'clinical_trials', name: 'Clinical Trials Management', category: 'Industry Specific' },
    { id: 'medical_records', name: 'Medical Records Management', category: 'Industry Specific' },
    { id: 'insurance_verification', name: 'Insurance Verification', category: 'Industry Specific' },
    { id: 'lab_results', name: 'Lab Results Integration', category: 'Industry Specific' },
    { id: 'real_estate_crm', name: 'Real Estate CRM', category: 'Industry Specific' },
    { id: 'property_listings', name: 'Property Listings Management', category: 'Industry Specific' },
    { id: 'virtual_tours', name: 'Virtual Property Tours', category: 'Industry Specific' },
    { id: 'mortgage_calculator', name: 'Mortgage Calculator', category: 'Industry Specific' },
    { id: 'tenant_screening', name: 'Tenant Screening', category: 'Industry Specific' },
    { id: 'lease_management', name: 'Lease Management', category: 'Industry Specific' },
    { id: 'property_maintenance', name: 'Property Maintenance', category: 'Industry Specific' },
    { id: 'rental_payments', name: 'Rental Payment Processing', category: 'Industry Specific' },
    { id: 'hoa_management', name: 'HOA Management', category: 'Industry Specific' },
    { id: 'mls_integration', name: 'MLS Integration', category: 'Industry Specific' },
    { id: 'legal_case_management', name: 'Legal Case Management', category: 'Industry Specific' },
    { id: 'contract_review', name: 'Contract Review & Analysis', category: 'Industry Specific' },
    { id: 'legal_research', name: 'Legal Research Tools', category: 'Industry Specific' },
    { id: 'court_calendar', name: 'Court Calendar Management', category: 'Industry Specific' },
    { id: 'document_discovery', name: 'Document Discovery', category: 'Industry Specific' },
    { id: 'client_intake', name: 'Client Intake Forms', category: 'Industry Specific' },
    { id: 'legal_billing', name: 'Legal Billing & Timekeeping', category: 'Industry Specific' },
    { id: 'compliance_legal', name: 'Legal Compliance Tracking', category: 'Industry Specific' },
    { id: 'litigation_support', name: 'Litigation Support', category: 'Industry Specific' },
    { id: 'ip_management', name: 'IP Management', category: 'Industry Specific' },
    { id: 'restaurant_pos', name: 'Restaurant POS', category: 'Industry Specific' },
    { id: 'table_reservations', name: 'Table Reservations', category: 'Industry Specific' },
    { id: 'menu_management', name: 'Menu Management', category: 'Industry Specific' },
    { id: 'food_delivery', name: 'Food Delivery Integration', category: 'Industry Specific' },
    { id: 'kitchen_display', name: 'Kitchen Display System', category: 'Industry Specific' },
    { id: 'ingredient_tracking', name: 'Ingredient Tracking', category: 'Industry Specific' },
    { id: 'recipe_costing', name: 'Recipe Costing', category: 'Industry Specific' },
    { id: 'staff_scheduling_restaurant', name: 'Restaurant Staff Scheduling', category: 'Industry Specific' },
    { id: 'loyalty_dining', name: 'Dining Loyalty Programs', category: 'Industry Specific' },
    { id: 'waitlist_management', name: 'Waitlist Management', category: 'Industry Specific' },
    { id: 'student_information', name: 'Student Information System', category: 'Industry Specific' },
    { id: 'gradebook', name: 'Digital Gradebook', category: 'Industry Specific' },
    { id: 'attendance_school', name: 'School Attendance Tracking', category: 'Industry Specific' },
    { id: 'parent_portal', name: 'Parent Portal', category: 'Industry Specific' },
    { id: 'curriculum_planning', name: 'Curriculum Planning', category: 'Industry Specific' },
    { id: 'assignment_submission', name: 'Assignment Submission', category: 'Industry Specific' },
    { id: 'exam_proctoring', name: 'Online Exam Proctoring', category: 'Industry Specific' },
    { id: 'library_management', name: 'Library Management System', category: 'Industry Specific' },
    { id: 'school_communication', name: 'School Communication Platform', category: 'Industry Specific' },
    { id: 'tuition_management', name: 'Tuition Management', category: 'Industry Specific' }
  ],

  // AI & Automation Skills (50 skills)
  'AI & Automation': [
    { id: 'chatbot_builder', name: 'Chatbot Builder', category: 'AI & Automation' },
    { id: 'virtual_assistant', name: 'Virtual Assistant', category: 'AI & Automation' },
    { id: 'voice_assistant', name: 'Voice Assistant', category: 'AI & Automation' },
    { id: 'natural_language', name: 'Natural Language Understanding', category: 'AI & Automation' },
    { id: 'intent_recognition', name: 'Intent Recognition', category: 'AI & Automation' },
    { id: 'entity_extraction', name: 'Entity Extraction', category: 'AI & Automation' },
    { id: 'sentiment_ai', name: 'Sentiment Analysis AI', category: 'AI & Automation' },
    { id: 'emotion_detection', name: 'Emotion Detection', category: 'AI & Automation' },
    { id: 'text_generation', name: 'Text Generation', category: 'AI & Automation' },
    { id: 'content_ai', name: 'AI Content Creation', category: 'AI & Automation' },
    { id: 'image_recognition', name: 'Image Recognition', category: 'AI & Automation' },
    { id: 'ocr', name: 'OCR Processing', category: 'AI & Automation' },
    { id: 'document_extraction', name: 'Document Extraction', category: 'AI & Automation' },
    { id: 'form_recognition', name: 'Form Recognition', category: 'AI & Automation' },
    { id: 'rpa', name: 'Robotic Process Automation', category: 'AI & Automation' },
    { id: 'workflow_ai', name: 'AI Workflow Optimization', category: 'AI & Automation' },
    { id: 'decision_automation', name: 'Decision Automation', category: 'AI & Automation' },
    { id: 'predictive_maintenance', name: 'Predictive Maintenance', category: 'AI & Automation' },
    { id: 'demand_forecasting', name: 'Demand Forecasting', category: 'AI & Automation' },
    { id: 'recommendation_engine', name: 'Recommendation Engine', category: 'AI & Automation' },
    { id: 'personalization_ai', name: 'AI Personalization', category: 'AI & Automation' },
    { id: 'dynamic_pricing_ai', name: 'Dynamic Pricing AI', category: 'AI & Automation' },
    { id: 'fraud_detection', name: 'Fraud Detection', category: 'AI & Automation' },
    { id: 'risk_scoring', name: 'Risk Scoring', category: 'AI & Automation' },
    { id: 'credit_scoring', name: 'Credit Scoring', category: 'AI & Automation' },
    { id: 'churn_prediction', name: 'Churn Prediction', category: 'AI & Automation' },
    { id: 'lead_scoring_ai', name: 'AI Lead Scoring', category: 'AI & Automation' },
    { id: 'customer_lifetime', name: 'Customer Lifetime Value', category: 'AI & Automation' },
    { id: 'ab_testing_ai', name: 'AI A/B Testing', category: 'AI & Automation' },
    { id: 'optimization_ai', name: 'AI Optimization', category: 'AI & Automation' },
    { id: 'scheduling_ai', name: 'AI Scheduling', category: 'AI & Automation' },
    { id: 'route_optimization', name: 'Route Optimization', category: 'AI & Automation' },
    { id: 'resource_ai', name: 'AI Resource Allocation', category: 'AI & Automation' },
    { id: 'quality_ai', name: 'AI Quality Control', category: 'AI & Automation' },
    { id: 'compliance_ai', name: 'AI Compliance Monitoring', category: 'AI & Automation' },
    { id: 'speech_to_text', name: 'Speech to Text', category: 'AI & Automation' },
    { id: 'text_to_speech', name: 'Text to Speech', category: 'AI & Automation' },
    { id: 'language_translation', name: 'Language Translation AI', category: 'AI & Automation' },
    { id: 'summarization', name: 'Text Summarization', category: 'AI & Automation' },
    { id: 'keyword_extraction', name: 'Keyword Extraction', category: 'AI & Automation' },
    { id: 'topic_modeling', name: 'Topic Modeling', category: 'AI & Automation' },
    { id: 'semantic_search', name: 'Semantic Search', category: 'AI & Automation' },
    { id: 'knowledge_graph', name: 'Knowledge Graph', category: 'AI & Automation' },
    { id: 'question_answering', name: 'Question Answering System', category: 'AI & Automation' },
    { id: 'document_understanding', name: 'Document Understanding', category: 'AI & Automation' },
    { id: 'video_analysis', name: 'Video Analysis AI', category: 'AI & Automation' },
    { id: 'audio_analysis', name: 'Audio Analysis', category: 'AI & Automation' },
    { id: 'facial_recognition', name: 'Facial Recognition', category: 'AI & Automation' },
    { id: 'object_detection', name: 'Object Detection', category: 'AI & Automation' }
  ],

  // Specialized Technical Skills (40 skills)
  'Technical & API': [
    { id: 'rest_api', name: 'REST API Integration', category: 'Technical & API' },
    { id: 'graphql', name: 'GraphQL Integration', category: 'Technical & API' },
    { id: 'webhook_management', name: 'Webhook Management', category: 'Technical & API' },
    { id: 'oauth_integration', name: 'OAuth Integration', category: 'Technical & API' },
    { id: 'api_gateway', name: 'API Gateway Management', category: 'Technical & API' },
    { id: 'rate_limiting', name: 'Rate Limiting', category: 'Technical & API' },
    { id: 'api_versioning', name: 'API Versioning', category: 'Technical & API' },
    { id: 'sdk_generation', name: 'SDK Generation', category: 'Technical & API' },
    { id: 'api_documentation', name: 'API Documentation', category: 'Technical & API' },
    { id: 'api_testing', name: 'API Testing Automation', category: 'Technical & API' },
    { id: 'database_sync', name: 'Database Synchronization', category: 'Technical & API' },
    { id: 'data_migration', name: 'Data Migration Tools', category: 'Technical & API' },
    { id: 'batch_processing', name: 'Batch Processing', category: 'Technical & API' },
    { id: 'stream_processing', name: 'Stream Processing', category: 'Technical & API' },
    { id: 'event_sourcing', name: 'Event Sourcing', category: 'Technical & API' },
    { id: 'cqrs', name: 'CQRS Implementation', category: 'Technical & API' },
    { id: 'microservices', name: 'Microservices Architecture', category: 'Technical & API' },
    { id: 'serverless', name: 'Serverless Computing', category: 'Technical & API' },
    { id: 'edge_computing', name: 'Edge Computing', category: 'Technical & API' },
    { id: 'iot_integration', name: 'IoT Device Integration', category: 'Technical & API' },
    { id: 'mqtt', name: 'MQTT Protocol', category: 'Technical & API' },
    { id: 'websocket', name: 'WebSocket Connections', category: 'Technical & API' },
    { id: 'grpc', name: 'gRPC Communication', category: 'Technical & API' },
    { id: 'message_queue', name: 'Message Queue Systems', category: 'Technical & API' },
    { id: 'pub_sub', name: 'Pub/Sub Messaging', category: 'Technical & API' },
    { id: 'circuit_breaker', name: 'Circuit Breaker Pattern', category: 'Technical & API' },
    { id: 'service_mesh', name: 'Service Mesh', category: 'Technical & API' },
    { id: 'load_balancing', name: 'Load Balancing', category: 'Technical & API' },
    { id: 'caching_strategy', name: 'Caching Strategy', category: 'Technical & API' },
    { id: 'cdn_management', name: 'CDN Management', category: 'Technical & API' },
    { id: 'ssl_certificates', name: 'SSL Certificate Management', category: 'Technical & API' },
    { id: 'dns_management', name: 'DNS Management', category: 'Technical & API' },
    { id: 'reverse_proxy', name: 'Reverse Proxy Setup', category: 'Technical & API' },
    { id: 'api_monitoring', name: 'API Monitoring', category: 'Technical & API' },
    { id: 'synthetic_monitoring', name: 'Synthetic Monitoring', category: 'Technical & API' },
    { id: 'distributed_tracing', name: 'Distributed Tracing', category: 'Technical & API' },
    { id: 'log_aggregation', name: 'Log Aggregation', category: 'Technical & API' },
    { id: 'metrics_collection', name: 'Metrics Collection', category: 'Technical & API' },
    { id: 'alerting_system', name: 'Alerting System', category: 'Technical & API' },
    { id: 'chaos_engineering', name: 'Chaos Engineering', category: 'Technical & API' }
  ],

  // Social Media & Content Creation (35 skills)
  'Social & Content': [
    { id: 'social_listening', name: 'Social Media Listening', category: 'Social & Content' },
    { id: 'hashtag_analytics', name: 'Hashtag Analytics', category: 'Social & Content' },
    { id: 'influencer_discovery', name: 'Influencer Discovery', category: 'Social & Content' },
    { id: 'content_curation', name: 'Content Curation', category: 'Social & Content' },
    { id: 'social_contests', name: 'Social Media Contests', category: 'Social & Content' },
    { id: 'ugc_management', name: 'UGC Management', category: 'Social & Content' },
    { id: 'social_commerce', name: 'Social Commerce', category: 'Social & Content' },
    { id: 'live_streaming', name: 'Live Streaming Management', category: 'Social & Content' },
    { id: 'story_creation', name: 'Story Creation Tools', category: 'Social & Content' },
    { id: 'reel_creation', name: 'Reel/Short Video Creation', category: 'Social & Content' },
    { id: 'social_crm', name: 'Social CRM', category: 'Social & Content' },
    { id: 'community_moderation', name: 'Community Moderation', category: 'Social & Content' },
    { id: 'social_customer_service', name: 'Social Customer Service', category: 'Social & Content' },
    { id: 'brand_advocacy', name: 'Brand Advocacy Programs', category: 'Social & Content' },
    { id: 'social_roi', name: 'Social Media ROI Tracking', category: 'Social & Content' },
    { id: 'content_planning', name: 'Content Planning', category: 'Social & Content' },
    { id: 'editorial_calendar', name: 'Editorial Calendar', category: 'Social & Content' },
    { id: 'content_approval', name: 'Content Approval Workflow', category: 'Social & Content' },
    { id: 'brand_guidelines', name: 'Brand Guidelines Enforcement', category: 'Social & Content' },
    { id: 'content_localization', name: 'Content Localization', category: 'Social & Content' },
    { id: 'content_versioning', name: 'Content Versioning', category: 'Social & Content' },
    { id: 'digital_asset_management', name: 'Digital Asset Management', category: 'Social & Content' },
    { id: 'content_distribution', name: 'Content Distribution', category: 'Social & Content' },
    { id: 'content_monetization', name: 'Content Monetization', category: 'Social & Content' },
    { id: 'podcast_distribution', name: 'Podcast Distribution', category: 'Social & Content' },
    { id: 'video_hosting', name: 'Video Hosting & Streaming', category: 'Social & Content' },
    { id: 'content_analytics', name: 'Content Performance Analytics', category: 'Social & Content' },
    { id: 'engagement_analytics', name: 'Engagement Analytics', category: 'Social & Content' },
    { id: 'competitor_content', name: 'Competitor Content Analysis', category: 'Social & Content' },
    { id: 'trending_topics', name: 'Trending Topics Discovery', category: 'Social & Content' },
    { id: 'content_ideation', name: 'Content Ideation Tools', category: 'Social & Content' },
    { id: 'seo_content', name: 'SEO Content Optimization', category: 'Social & Content' },
    { id: 'content_repurposing', name: 'Content Repurposing', category: 'Social & Content' },
    { id: 'interactive_content', name: 'Interactive Content Creation', category: 'Social & Content' },
    { id: 'ar_filters', name: 'AR Filter Creation', category: 'Social & Content' }
  ]
};

// Helper function to get all skills count
export function getTotalSkillsCount(): number {
  return Object.values(SKILLS_CATALOG).reduce((total, skills) => total + skills.length, 0);
}

// Helper function to get skills by agent type
export function getSkillsByAgentType(agentType: string): Skill[] {
  switch(agentType) {
    case 'sales':
      return [
        ...SKILLS_CATALOG['Sales & CRM'],
        ...SKILLS_CATALOG['Marketing & Content'].slice(0, 10),
        ...SKILLS_CATALOG['Communication'].slice(0, 5)
      ];
    case 'support':
      return [
        ...SKILLS_CATALOG['Customer Support'],
        ...SKILLS_CATALOG['Communication'].slice(0, 10),
        ...SKILLS_CATALOG['AI & Automation'].slice(0, 5)
      ];
    case 'marketing':
      return [
        ...SKILLS_CATALOG['Marketing & Content'],
        ...SKILLS_CATALOG['Data & Analytics'].slice(0, 10),
        ...SKILLS_CATALOG['AI & Automation'].slice(0, 8)
      ];
    case 'operations':
      return [
        ...SKILLS_CATALOG['Operations & Workflow'],
        ...SKILLS_CATALOG['Finance & Accounting'].slice(0, 10),
        ...SKILLS_CATALOG['HR & People'].slice(0, 5)
      ];
    case 'data':
      return [
        ...SKILLS_CATALOG['Data & Analytics'],
        ...SKILLS_CATALOG['AI & Automation'].slice(0, 15)
      ];
    default:
      // Return a mix of essential skills for custom agents
      return [
        ...SKILLS_CATALOG['Operations & Workflow'].slice(0, 10),
        ...SKILLS_CATALOG['Communication'].slice(0, 10),
        ...SKILLS_CATALOG['AI & Automation'].slice(0, 10)
      ];
  }
}

// Export total count for easy reference
export const TOTAL_SKILLS = getTotalSkillsCount(); // Now 500+ skills